import { useState, useEffect, useRef } from "react";
import toast from "react-hot-toast";
import { useParams, useNavigate } from "react-router-dom";
import api from "../api/axiosInstance";
import ViolationModal from "../components/ViolationModal";
import {
    Shield, Play, Timer, ArrowRight, ArrowLeft,
    Lock, AlertCircle, Terminal, Cpu, Zap,
    CheckCircle2, Info, ChevronRight, Activity, Radar,
    AlertTriangle, ShieldAlert, Camera, Mic, Wifi, Server
} from "lucide-react";
import { Editor } from "@monaco-editor/react";

export default function CandidateAssessment() {
    const { assessmentId } = useParams();
    const navigate = useNavigate();
    const [submissionId, setSubmissionId] = useState(null);
    const [questions, setQuestions] = useState([]);
    const [answers, setAnswers] = useState({});
    const [loading, setLoading] = useState(true);
    const [submitting, setSubmitting] = useState(false);

    // Proctoring & Status State
    const [examStarted, setExamStarted] = useState(false);
    const [isFullscreen, setIsFullscreen] = useState(false);
    const [violationType, setViolationType] = useState(null);
    const [isModalOpen, setIsModalOpen] = useState(false);

    // Behavioral Biometrics State (Using a ref to avoid stale closures in event listeners)
    const metricsRef = useRef({
        keypressPatterns: [],
        lastKeyTime: 0,
        focusLostCount: 0,
        backspaceCount: 0,
        answerChanges: 0,
        copyPasteAttempts: 0
    });

    // Section/Timer State
    const [currentSection, setCurrentSection] = useState("MCQ"); // MCQ, SUBJECTIVE, CODING
    const [timeLeft, setTimeLeft] = useState(0);
    const timerRef = useRef(null);

    useEffect(() => {
        initializeSession();
    }, [assessmentId]);

    // Start Timer when section changes
    useEffect(() => {
        if (examStarted && !isModalOpen) {
            startSectionTimer();
        }
        return () => clearInterval(timerRef.current);
    }, [currentSection, examStarted, isModalOpen]);

    const initializeSession = async () => {
        try {
            const { data } = await api.post("/api/submissions/start", { assessmentId });
            setSubmissionId(data.submissionId);
            const res = await api.get(`/api/assessments/${assessmentId}`);
            if (!res.data || res.data.length === 0) {
                toast.error("Assessment questions are still being generated by the AI kernel. Please try again in 30 seconds.");
                navigate("/candidate/dashboard");
                return;
            }
            setQuestions(res.data);
            setLoading(false);
        } catch (error) {
            console.error("Session Init Error:", error);
            const errorMsg = error.response?.data?.error || "Failed to initialize assessment session.";
            toast.error(errorMsg);
            navigate("/candidate/dashboard");
        }
    };

    useEffect(() => {
        if (examStarted) {
            window.addEventListener("visibilitychange", handleVisibilityChange);
            window.addEventListener("blur", handleBlur);
            window.addEventListener("keydown", handleKeyDown);
            document.addEventListener("fullscreenchange", handleFullscreenChange);
            window.addEventListener("copy", blockEvent);
            window.addEventListener("paste", blockEvent);
            window.addEventListener("contextmenu", blockEvent);
        }
        return () => {
            window.removeEventListener("visibilitychange", handleVisibilityChange);
            window.removeEventListener("blur", handleBlur);
            window.removeEventListener("keydown", handleKeyDown);
            document.removeEventListener("fullscreenchange", handleFullscreenChange);
            window.removeEventListener("copy", blockEvent);
            window.removeEventListener("paste", blockEvent);
            window.removeEventListener("contextmenu", blockEvent);
        };
    }, [examStarted]);

    const handleFullscreenChange = () => {
        const isFull = !!document.fullscreenElement;
        setIsFullscreen(isFull);
        if (examStarted && !isFull) {
            triggerViolation("FULLSCREEN_EXIT");
        }
    };

    const handleVisibilityChange = () => {
        if (document.hidden && examStarted) {
            metricsRef.current.focusLostCount++;
            triggerViolation("TAB_SWITCH_OR_NOTIFICATION");
        }
    };

    const handleBlur = () => {
        if (examStarted) {
            metricsRef.current.focusLostCount++;
            triggerViolation("TAB_SWITCH_OR_NOTIFICATION");
        }
    };

    const handleKeyDown = (e) => {
        const now = Date.now();
        if (metricsRef.current.lastKeyTime > 0) {
            const latency = now - metricsRef.current.lastKeyTime;
            metricsRef.current.keypressPatterns.push(latency);
            if (metricsRef.current.keypressPatterns.length > 20) {
                metricsRef.current.keypressPatterns.shift();
            }
        }
        metricsRef.current.lastKeyTime = now;

        // Track backspaces as a behavioral biometric
        if (e.key === 'Backspace') metricsRef.current.backspaceCount++;

        if (e.key === 'Escape' && examStarted) triggerViolation('FULLSCREEN_EXIT');

        // Distinguish copy-paste from other Ctrl combos
        if ((e.ctrlKey || e.metaKey) && examStarted) {
            if (e.key === 'c' || e.key === 'v' || e.key === 'x') {
                metricsRef.current.copyPasteAttempts++;
                triggerViolation('COPY_PASTE_ATTEMPT');
            } else if (e.key !== 'a') {
                // Block other dangerous Ctrl combos (not Ctrl+A select-all)
                triggerViolation('HOTKEY_BYPASS_ATTEMPT');
            }
        }
    };

    const blockEvent = (e) => {
        e.preventDefault();
        return false;
    };

    const triggerViolation = async (type) => {
        if (isModalOpen) return;
        setViolationType(type);
        setIsModalOpen(true);
        setExamStarted(false);
        clearInterval(timerRef.current);

        try {
            await api.post('/api/submissions/violation', {
                assessment_id: assessmentId,
                violation_type: type,
                timestamp: new Date().toISOString(),
                auto_submitted: true,
                // Full behavioral biometrics payload
                biometrics: {
                    keypress_patterns: [...metricsRef.current.keypressPatterns],
                    focus_lost_count: metricsRef.current.focusLostCount,
                    backspace_count: metricsRef.current.backspaceCount,
                    copy_paste_attempts: metricsRef.current.copyPasteAttempts,
                    answer_changes: metricsRef.current.answerChanges,
                    avg_keystroke_latency_ms: metricsRef.current.keypressPatterns.length > 0
                        ? Math.round(metricsRef.current.keypressPatterns.reduce((a, b) => a + b, 0) / metricsRef.current.keypressPatterns.length)
                        : 0
                }
            });
            await handleSubmit(true);
        } catch (err) {
            console.error('Violation Sync Failure:', err);
        }
    };

    const startSectionTimer = () => {
        clearInterval(timerRef.current);
        const sectionQuestions = questions.filter(q => q.type === currentSection);
        let duration = 0;

        if (currentSection === "MCQ") duration = sectionQuestions.length * 60;
        else if (currentSection === "SUBJECTIVE") duration = sectionQuestions.length * 240;
        else if (currentSection === "CODING") duration = 1200; // 20 mins for coding

        setTimeLeft(duration);
        timerRef.current = setInterval(() => {
            setTimeLeft(prev => {
                if (prev <= 1) {
                    clearInterval(timerRef.current);
                    handleTimeOut();
                    return 0;
                }
                return prev - 1;
            });
        }, 1000);
    };

    const handleTimeOut = () => {
        if (currentSection === "MCQ") setCurrentSection("SUBJECTIVE");
        else if (currentSection === "SUBJECTIVE") setCurrentSection("CODING");
        else handleSubmit(true);
    };

    const enterFullscreen = () => {
        const elem = document.documentElement;
        if (elem.requestFullscreen) {
            elem.requestFullscreen();
        } else if (elem.webkitRequestFullscreen) { /* Safari */
            elem.webkitRequestFullscreen();
        } else if (elem.msRequestFullscreen) { /* IE11 */
            elem.msRequestFullscreen();
        }
        setIsFullscreen(true);
    };

    const startExam = () => {
        if (!isFullscreen) return;
        setExamStarted(true);
    };

    const handleSubmit = async (isAuto = false) => {
        setSubmitting(true);
        try {
            await api.post("/api/submissions", {
                submissionId,
                answers: answers
            });
            if (!isAuto) {
                navigate(`/candidate/result/${submissionId}`);
            }
        } catch (error) {
            console.error("Submission Error:", error);
            toast.error("Critical submission error. Attempting to save...");
        } finally {
            setSubmitting(false);
        }
    };

    const handleAnswerChange = (questionId, value, lang = null) => {
        metricsRef.current.answerChanges++;
        if (lang) {
            setAnswers(prev => ({ ...prev, [questionId]: { code: value, lang } }));
        } else {
            setAnswers(prev => ({ ...prev, [questionId]: value }));
        }
    };

    if (loading) return (
        <div className="min-h-screen bg-[#020204] flex flex-col items-center justify-center font-cyber text-teal-400 overflow-hidden relative">
            <div className="noise-overlay" />
            <div className="absolute inset-0 bg-glow-teal opacity-20 pointer-events-none animate-pulse" />
            <div className="relative">
                <div className="w-24 h-24 border-2 border-teal-500/10 border-t-teal-500 rounded-full animate-[spin_2s_linear_infinite] mb-8" />
                <div className="absolute inset-0 flex items-center justify-center">
                    <Activity size={24} className="animate-pulse" />
                </div>
            </div>
            <div className="tracking-[0.8em] animate-pulse text-[10px] font-bold uppercase text-slate-500">Decrypting_Secure_Protocol...</div>
        </div>
    );

    if (!examStarted && !isModalOpen) {
        return (
            <PreExamScreen
                isFullscreen={isFullscreen}
                onEnterFullscreen={enterFullscreen}
                onStart={startExam}
            />
        );
    }

    const currentQuestions = questions.filter(q => q.type === currentSection);

    return (
        <div className="min-h-screen bg-[#020204] text-slate-300 p-6 font-sans select-none pb-32 relative overflow-hidden">
            <ViolationModal
                isOpen={isModalOpen}
                type={violationType}
                onExit={() => navigate("/candidate/dashboard")}
            />

            {/* Left HUD: System Monitor */}
            <div className="fixed left-8 top-1/2 -translate-y-1/2 w-16 space-y-8 z-50 hidden lg:flex flex-col items-center">
                <div className="flex flex-col items-center gap-2">
                    <div className="h-40 w-1 bg-white/5 rounded-full relative overflow-hidden">
                        <div
                            className="absolute bottom-0 w-full bg-teal-500 shadow-[0_0_10px_rgba(20,184,166,0.5)] transition-all duration-1000"
                            style={{ height: '85%' }}
                        ></div>
                    </div>
                    <span className="text-[8px] font-black text-gray-600 vertical-text uppercase tracking-widest">SYSTEM_HEALTH</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                    <div className="h-40 w-1 bg-white/5 rounded-full relative overflow-hidden">
                        <div
                            className="absolute bottom-0 w-full bg-red-500 shadow-[0_0_10px_rgba(239,68,68,0.5)] transition-all duration-1000"
                            style={{ height: `${Math.min(metricsRef.current.focusLostCount * 20, 100)}%` }}
                        ></div>
                    </div>
                    <span className="text-[8px] font-black text-gray-600 vertical-text uppercase tracking-widest">THREAT_LEVEL</span>
                </div>
            </div>

            {/* Top HUD: Command Bar */}
            <header className="max-w-7xl mx-auto mb-10 sticky top-0 z-40 px-4">
                <div className="glass-card bg-black/80 backdrop-blur-3xl px-8 py-4 flex justify-between items-center border-teal-500/20 shadow-[0_20px_50px_rgba(0,0,0,0.5)]">
                    <div className="flex items-center gap-8">
                        <div className="flex items-center gap-3">
                            <div className="p-2.5 bg-teal-500/10 rounded-xl border border-teal-500/20">
                                <Radar className="text-teal-500 animate-pulse" size={18} />
                            </div>
                            <div>
                                <h1 className="text-lg font-black text-white italic tracking-tighter font-cyber uppercase leading-none">NEUROX_SHELL_v4.5</h1>
                                <p className="text-[8px] text-gray-600 font-bold uppercase tracking-[0.4em] mt-1">SECURE_ENVIRONMENT / ACTIVE</p>
                            </div>
                        </div>
                        <div className="h-8 w-px bg-white/5"></div>
                        <div className="flex flex-col">
                            <span className="text-[9px] font-black text-gray-600 uppercase tracking-widest uppercase">CURRENT_NODE:</span>
                            <span className="text-[10px] text-teal-500 font-black tracking-[0.2em]">{currentSection} EVALUATION</span>
                        </div>
                    </div>

                    <div className="flex items-center gap-10">
                        <div className="flex flex-col items-end">
                            <div className="flex items-center gap-2 mb-0.5">
                                <div className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse"></div>
                                <span className="text-[9px] font-black text-red-500 uppercase tracking-widest">LOG_REMAINING:</span>
                            </div>
                            <div className="text-2xl font-black text-white font-cyber tracking-tighter tabular-nums italic">
                                {Math.floor(timeLeft / 60)}:{String(timeLeft % 60).padStart(2, '0')}
                            </div>
                        </div>
                        <div className="flex gap-1.5">
                            {[1, 2, 3].map(i => (
                                <div key={i} className={`w-1 h-6 rounded-full ${i <= 2 ? 'bg-teal-500/40' : 'bg-white/5'}`}></div>
                            ))}
                        </div>
                    </div>
                </div>
            </header>

            <main className="max-w-5xl mx-auto space-y-24 relative z-10 px-4 animate-in fade-in slide-in-from-bottom-8 duration-1000">
                {currentQuestions.map((q, idx) => (
                    <QuestionBox
                        key={q.id}
                        idx={idx}
                        question={q}
                        value={answers[q.id] || ''}
                        onChange={(val, lang) => handleAnswerChange(q.id, val, lang)}
                        api={api}
                    />
                ))}

                <footer className="pt-12 flex flex-col items-center gap-8">
                    <div className="flex items-center gap-10 text-gray-600">
                        <div className="flex items-center gap-3">
                            <ShieldAlert size={14} className="text-teal-500/50" />
                            <span className="text-[9px] font-black uppercase tracking-widest">Active_Kernel_Hash: 0x82...F429</span>
                        </div>
                        <div className="flex items-center gap-3">
                            <Lock size={14} className="text-teal-500/50" />
                            <span className="text-[9px] font-black uppercase tracking-widest">Encryption: SHA-256</span>
                        </div>
                        <div className="flex items-center gap-3">
                            <Activity size={14} className="text-teal-500/50" />
                            <span className="text-[9px] font-black uppercase tracking-widest">Sync_Status: NOMINAL</span>
                        </div>
                    </div>

                    {currentSection !== "CODING" ? (
                        <button
                            onClick={handleTimeOut}
                            className="cyber-button cyber-button-primary px-10 py-4 flex items-center gap-3 group text-sm font-black italic tracking-tighter"
                        >
                            COMMIT_AND_NEXT_PROTOCOL <ChevronRight size={16} className="group-hover:translate-x-1.5 transition-transform" />
                        </button>
                    ) : (
                        <button
                            onClick={() => handleSubmit(false)}
                            disabled={submitting}
                            className="cyber-button bg-white text-black hover:bg-teal-400 px-16 py-4 rounded-2xl flex items-center gap-3 group text-sm font-black italic tracking-tighter shadow-2xl"
                        >
                            {submitting ? 'TERMINATING_SESSION...' : <>FINAL_SYSTEM_DISCONNECT <CheckCircle2 size={18} /></>}
                        </button>
                    )}
                </footer>
            </main>

            {/* Background HUD Grid */}
            <div className="fixed inset-0 pointer-events-none opacity-20">
                <div className="absolute top-1/4 left-10 w-px h-64 bg-gradient-to-b from-transparent via-teal-500 to-transparent"></div>
                <div className="absolute top-1/4 right-10 w-px h-64 bg-gradient-to-b from-transparent via-teal-500 to-transparent"></div>
                <div className="absolute top-1/2 left-0 w-full h-px bg-gradient-to-r from-transparent via-teal-500/10 to-transparent"></div>
            </div>
        </div>
    );
}

function PreExamScreen({ isFullscreen, onEnterFullscreen, onStart }) {
    const [scanState, setScanState] = useState(0); 

    useEffect(() => {
        if (!isFullscreen) return;
        
        let timer1 = setTimeout(() => setScanState(1), 1000);
        let timer2 = setTimeout(() => setScanState(2), 2500);
        let timer3 = setTimeout(() => setScanState(3), 4000);

        return () => { clearTimeout(timer1); clearTimeout(timer2); clearTimeout(timer3); };
    }, [isFullscreen]);

    return (
        <div className="min-h-screen bg-[#020204] flex items-center justify-center p-12 font-sans overflow-hidden relative">
            <div className="noise-overlay" />
            <div className="scanline" />
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-glow-teal opacity-20 pointer-events-none" />

            <div className="max-w-4xl w-full glass-card p-12 space-y-12 relative overflow-hidden bg-black/60 border-teal-500/20 shadow-[0_50px_100px_rgba(0,0,0,0.8)] animate-in zoom-in-95 duration-1000">
                <div className="absolute top-0 right-0 p-10 opacity-[0.02] text-[120px] font-black font-cyber select-none italic tracking-tighter underline">AUTH</div>

                <div className="flex flex-col md:flex-row items-center justify-between gap-10 relative z-10 border-b border-white/5 pb-10">
                    <div className="flex items-center gap-6">
                        <div className="w-16 h-16 bg-teal-500 flex items-center justify-center rounded-[1.5rem] shadow-[0_0_40px_rgba(20,184,166,0.6)]">
                            <Shield size={32} className="text-black" />
                        </div>
                        <div>
                            <div className="flex items-center gap-2.5 mb-1.5">
                                <span className="px-2 py-0.5 bg-teal-500/10 border border-teal-500/30 text-teal-400 font-black text-[9px] rounded uppercase tracking-[0.2em]">PROTOCOL_X_V4.0</span>
                                <div className="w-1.5 h-1.5 rounded-full bg-green-500 animate-glow"></div>
                            </div>
                            <h1 className="text-3xl font-black text-white tracking-widest uppercase italic font-cyber leading-none">SYSTEM_CHECK</h1>
                            <p className="text-[10px] text-gray-600 font-bold uppercase tracking-[0.6em] mt-2">NeuroX_Enforcement_Kernel</p>
                        </div>
                    </div>
                </div>

                {!isFullscreen ? (
                    <div className="space-y-8 flex flex-col items-center justify-center py-10">
                        <div className="w-24 h-24 border-2 border-teal-500/20 border-t-teal-500 rounded-full animate-[spin_3s_linear_infinite] mb-4 relative flex items-center justify-center">
                            <Lock size={32} className="text-teal-500 animate-pulse absolute" />
                        </div>
                        <div className="text-center space-y-4">
                            <h3 className="text-xl font-black text-white uppercase italic tracking-widest font-cyber">Secure Environment Required</h3>
                            <p className="text-xs text-gray-500 uppercase tracking-widest leading-loose">The assessment kernel must run in full-screen mode to prevent unauthorized lateral movement.</p>
                        </div>
                        <button
                            onClick={onEnterFullscreen}
                            className="cyber-button cyber-button-primary px-12 py-5 text-xs font-black italic tracking-widest shadow-[0_0_30px_rgba(20,184,166,0.2)] animate-glow"
                        >
                            ENFORCE_ISOLATION_PROTOCOL
                        </button>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-10 relative z-10">
                        <div className="space-y-6">
                            <h3 className="text-[10px] font-black text-teal-500 uppercase tracking-[0.4em] font-cyber flex items-center gap-3"><Terminal size={14}/> SYSTEM_AUDIT_STREAM:</h3>
                            <div className="p-6 bg-black/80 border border-white/5 rounded-2xl font-mono text-xs leading-loose text-gray-500 h-[280px] overflow-hidden relative shadow-inner">
                                <div className="absolute top-0 left-0 w-full h-8 bg-gradient-to-b from-black/80 to-transparent z-10 pointer-events-none"></div>
                                <div className="absolute bottom-0 left-0 w-full h-8 bg-gradient-to-t from-black/80 to-transparent z-10 pointer-events-none"></div>
                                
                                <div className="space-y-2 translate-y-2 animate-in slide-in-from-bottom-12 duration-1000">
                                    <div className="text-teal-500/50">[{new Date().toISOString().split('T')[1].slice(0,-1)}] INITIALIZING_KERNEL...</div>
                                    <div className="text-white">[{new Date().toISOString().split('T')[1].slice(0,-1)}] FULLSCREEN_LOCK_ACQUIRED</div>
                                    {scanState >= 1 && <div className="text-teal-400">[{new Date().toISOString().split('T')[1].slice(0,-1)}] BIOMETRIC_SENSORS_ACTIVE</div>}
                                    {scanState >= 2 && <div className="text-blue-400">[{new Date().toISOString().split('T')[1].slice(0,-1)}] NETWORK_LATENCY_NOMINAL</div>}
                                    {scanState >= 3 && <div className="text-green-400 font-bold flash">[{new Date().toISOString().split('T')[1].slice(0,-1)}] ALL_SYSTEMS_GO_READY_FOR_EXECUTION</div>}
                                    {scanState < 3 && <div className="animate-pulse text-yellow-500">_waiting_for_node_response...</div>}
                                </div>
                            </div>
                        </div>

                        <div className="space-y-6">
                            <h3 className="text-[10px] font-black text-teal-500 uppercase tracking-[0.4em] font-cyber flex items-center gap-3"><Server size={14}/> HARDWARE_STATUS:</h3>
                            <div className="space-y-4">
                                <HardwareCheck icon={<Camera size={18} />} label="VISUAL_NODE (WEBCAM)" status={scanState >= 1} />
                                <HardwareCheck icon={<Mic size={18} />} label="AUDIO_NODE (MIC)" status={scanState >= 1} />
                                <HardwareCheck icon={<Wifi size={18} />} label="CONNECTION_STABILITY" status={scanState >= 2} />
                                <HardwareCheck icon={<Activity size={18} />} label="ENVIRONMENT_SCAN" status={scanState >= 3} />
                            </div>

                            <button
                                onClick={onStart}
                                disabled={scanState < 3}
                                className={`w-full py-5 text-xs font-black italic tracking-widest flex items-center justify-center gap-4 transition-all duration-700 rounded-2xl
                                    ${scanState === 3 ? 'cyber-button bg-white text-black hover:bg-teal-400 animate-glow shadow-[0_0_30px_rgba(255,255,255,0.3)]' : 'bg-white/5 text-gray-600 border border-white/10 cursor-not-allowed'}
                                `}
                            >
                                <Play size={18} className={scanState === 3 ? "scale-110" : ""} /> INITIALIZE_NEURAL_LINK
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}

function HardwareCheck({ icon, label, status }) {
    return (
        <div className={`flex items-center justify-between p-4 rounded-xl border ${status ? 'bg-teal-500/5 border-teal-500/20 text-teal-400' : 'bg-white/[0.02] border-white/5 text-gray-600'} transition-all duration-700`}>
            <div className="flex items-center gap-4">
                <div className={status ? 'animate-pulse' : ''}>{icon}</div>
                <span className="text-[10px] font-black uppercase tracking-widest">{label}</span>
            </div>
            <div className={`w-2 h-2 rounded-full ${status ? 'bg-teal-500 shadow-[0_0_10px_rgba(20,184,166,0.8)]' : 'bg-gray-700'}`}></div>
        </div>
    );
}

function QuestionBox({ idx, question, value, onChange, api }) {
    const [running, setRunning] = useState(false);
    const [results, setResults] = useState(null);
    const [selectedLang, setSelectedLang] = useState('python');

    const languages = [
        { id: 'python', name: 'Python 3', icon: '🐍' },
        { id: 'cpp', name: 'C++ 17', icon: '⚙️' },
        { id: 'java', name: 'Java 11', icon: '☕' }
    ];

    useEffect(() => {
        if (question.type === "CODING" && (!value || (typeof value === 'object' && !value.code))) {
            const boilerplate = question.content.starter_code?.[selectedLang] || '';
            onChange(boilerplate, selectedLang);
        }
    }, [question.id]);

    const handleRun = async () => {
        setRunning(true);
        try {
            const { data } = await api.post("/api/assessments/submit-code", {
                source_code: value?.code || value,
                language_id: selectedLang,
                test_cases: question.content.test_cases
            });
            setResults(data.results);
        } catch (err) {
            console.error(err);
            toast.error("Execution kernel error.");
        } finally {
            setRunning(false);
        }
    };

    if (question.type === "CODING") {
        return (
            <div className="glass-card flex flex-col lg:flex-row gap-0 overflow-hidden min-h-[750px] border-white/5 hover:border-teal-500/10 shadow-[0_50px_100px_rgba(0,0,0,0.5)] bg-[#020204]/80 group">
                <div className="scanline opacity-[0.03]"></div>
                {/* Problem Meta */}
                <div className="lg:w-[380px] p-10 border-r border-white/5 bg-white/[0.01] overflow-y-auto space-y-10 custom-scrollbar relative z-10">
                    <div className="flex justify-between items-center">
                        <span className="px-4 py-1.5 bg-teal-500 text-black font-black text-[9px] rounded-lg uppercase tracking-widest shadow-2xl">MISSION_STEP_{idx + 1}</span>
                        <div className="flex items-center gap-2.5">
                            <Zap size={12} className="text-teal-500" />
                            <span className="text-[9px] font-black text-gray-500 uppercase tracking-[0.2em]">TYPE: ALGORITHMIC</span>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <h2 className="text-xl font-black text-white uppercase italic tracking-tighter font-cyber flex items-center gap-3">
                            <ArrowRight size={20} className="text-teal-500" /> PROBLEM_SPEC:
                        </h2>
                        <div className="text-sm text-gray-400 leading-relaxed font-sans space-y-4">
                            {question.content.problem_statement.split('\n').map((line, i) => (
                                <p key={i}>{line}</p>
                            ))}
                        </div>
                    </div>

                    <div className="space-y-5 pt-8 border-t border-white/5">
                        <label className="text-[10px] font-black text-teal-400 uppercase tracking-[0.3em] flex items-center gap-3">
                            <Info size={14} /> DATA_CONSTRAINTS:
                        </label>
                        <div className="p-6 bg-black/80 border border-white/5 rounded-2xl text-[10px] font-mono text-gray-500 leading-loose shadow-inner italic">
                            {question.content.constraints || "Memory_Limit: 512MB\nTime_Limit: 2.0s\nStandard_I/O_Required\nEdge_Case_Stability: HIGH"}
                        </div>
                    </div>
                </div>

                {/* Editor Module */}
                <div className="flex-1 flex flex-col bg-[#050505] relative z-10">
                    <div className="px-8 py-4 bg-white/[0.02] border-b border-white/5 flex items-center justify-between">
                        <div className="flex items-center gap-5">
                            <div className="flex items-center gap-2.5 px-4 py-2 bg-black/60 rounded-xl border border-white/5">
                                <span className="text-[9px] font-black text-gray-600 uppercase tracking-widest">LANG:</span>
                                <select
                                    value={selectedLang}
                                    onChange={(e) => {
                                        setSelectedLang(e.target.value);
                                        const boilerplate = question.content.starter_code?.[e.target.value] || '';
                                        onChange(boilerplate, e.target.value);
                                    }}
                                    className="bg-transparent text-[10px] font-black text-white uppercase tracking-widest outline-none cursor-pointer"
                                >
                                    {languages.map(l => <option key={l.id} value={l.id} className="bg-black text-white">{l.name}</option>)}
                                </select>
                            </div>
                        </div>
                        <button
                            onClick={handleRun}
                            disabled={running}
                            className={`cyber-button ${running ? 'bg-gray-800' : 'cyber-button-primary shadow-2xl'} px-8 py-3 flex items-center gap-3 transition-all duration-500 font-black italic tracking-widest text-[11px]`}
                        >
                            {running ? 'RUNNING_DIAGNOSTICS...' : <>EXEC_DIAGNOSTICS <Play size={14} /></>}
                        </button>
                    </div>

                    <div className="flex-1 relative group bg-[#020204] pt-2">
                        <div className="absolute top-0 left-0 w-full h-full p-1 opacity-[0.02] pointer-events-none z-10">
                            <div className="w-full h-full border-2 border-white/5 rounded-sm"></div>
                        </div>
                        <Editor
                            height="100%"
                            theme="vs-dark"
                            language={selectedLang === 'cpp' ? 'cpp' : selectedLang}
                            value={value?.code || value || ''}
                            onChange={(newValue) => onChange(newValue, selectedLang)}
                            options={{
                                minimap: { enabled: false },
                                fontSize: 13,
                                fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
                                padding: { top: 20, bottom: 20 },
                                cursorBlinking: "smooth",
                                cursorSmoothCaretAnimation: "on",
                                smoothScrolling: true,
                                lineNumbersMinChars: 3,
                                scrollbar: {
                                    verticalScrollbarSize: 8,
                                    horizontalScrollbarSize: 8,
                                    verticalSliderSize: 4,
                                    horizontalSliderSize: 4
                                }
                            }}
                        />
                    </div>

                    {/* Results Overlay */}
                    {results && (
                        <div className="bg-black/95 backdrop-blur-3xl border-t border-white/10 p-8 animate-in slide-in-from-bottom duration-700 max-h-[350px] overflow-y-auto custom-scrollbar shadow-[0_-20px_100px_rgba(0,0,0,0.8)]">
                            <div className="flex justify-between items-center mb-8">
                                <div className="flex items-center gap-3">
                                    <div className="p-2.5 bg-teal-500/10 rounded-lg">
                                        <Activity size={16} className="text-teal-500" />
                                    </div>
                                    <h4 className="text-[10px] font-black text-white uppercase tracking-[0.4em] font-cyber">EXECUTION_REPORT_LOG</h4>
                                </div>
                                <div className="text-[9px] font-black text-black px-4 py-1.5 bg-teal-500 rounded-full uppercase tracking-[0.2em] shadow-[0_0_20px_rgba(20,184,166,0.5)] font-cyber">
                                    NODES_PASSED: {results.filter(r => r.passed).length}/{results.length}
                                </div>
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                {results.map((r, i) => (
                                    <div key={i} className={`p-6 border-2 rounded-[2rem] flex items-center justify-between transition-all ${r.passed ? 'border-teal-500/10 bg-teal-500/[0.02]' : 'border-red-500/10 bg-red-500/[0.02]'}`}>
                                        <div className="flex items-center gap-5">
                                            <div className={`w-3 h-3 rounded-full ${r.passed ? 'bg-teal-500 shadow-[0_0_10px_rgba(20,184,166,0.5)]' : 'bg-red-500 shadow-[0_0_10px_rgba(239,68,68,0.5)] animate-pulse'}`}></div>
                                            <div className="flex flex-col">
                                                <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest">DATA_POINT_{i + 1}</span>
                                                <span className="text-[9px] text-gray-700 font-bold uppercase mt-1 italic">{r.passed ? 'Verified_Secure' : 'Integrity_Violation'}</span>
                                            </div>
                                        </div>
                                        <div className="flex flex-col items-end">
                                            <span className={`text-[12px] font-black uppercase tracking-tighter italic ${r.passed ? 'text-teal-500' : 'text-red-500'}`}>{r.passed ? 'PASSED' : 'FAILED'}</span>
                                            {r.error && <span className="text-[8px] text-red-500/50 uppercase mt-1">ERROR_CODE: 0xRE7</span>}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}
                </div>
            </div>
        );
    }

    return (
        <section className="glass-card p-10 relative border-white/5 bg-white/[0.01] group hover:border-teal-500/20 transition-all duration-1000 shadow-[0_50px_100px_rgba(0,0,0,0.5)] animate-in fade-in duration-1000">
            <div className="absolute -top-3 -left-3 bg-teal-500 text-black px-5 py-2 rounded-xl font-black text-[10px] uppercase tracking-[0.3em] shadow-[0_10px_30px_rgba(20,184,166,0.3)] italic font-cyber">
                MISSION_SEGMENT_{idx + 1}
            </div>

            <div className="space-y-12">
                <div className="space-y-6">
                    <p className="text-xl font-black text-white leading-tight tracking-tight uppercase italic font-cyber underline decoration-teal-500/20 underline-offset-4 decoration-2">{question.content.question}</p>
                    <div className="flex gap-1.5 pt-2">
                        {[1, 2, 3, 4, 5].map(i => (
                            <div key={i} className={`w-8 h-1 rounded-full ${i <= 3 ? 'bg-teal-500/30' : 'bg-white/5'}`}></div>
                        ))}
                    </div>
                </div>

                {question.type === "MCQ" ? (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {question.content.options.map((opt, i) => {
                            const label = String.fromCharCode(65 + i);
                            const isSelected = (value?.code || value) === label;
                            return (
                                <button
                                    key={label}
                                    onClick={() => onChange(label)}
                                    className={`flex items-center gap-6 p-5 border-[1.5px] rounded-2xl transition-all duration-500 text-left group/opt relative overflow-hidden ${isSelected
                                        ? 'bg-teal-500/10 border-teal-500 shadow-[0_0_50px_rgba(20,184,166,0.15)] scale-[1.01]'
                                        : 'bg-black/60 border-white/5 hover:border-teal-500/30'
                                        }`}
                                >
                                    {isSelected && <div className="absolute right-0 top-0 p-3 opacity-10"><Zap size={48} className="text-teal-500" /></div>}
                                    <div className={`w-12 h-12 flex items-center justify-center rounded-2xl font-black text-xl transition-all duration-500 ${isSelected ? 'bg-teal-500 text-black shadow-[0_0_10px_rgba(20,184,166,0.5)] scale-110' : 'bg-white/5 text-gray-700'}`}>
                                        {label}
                                    </div>
                                    <div className="flex flex-col">
                                        <span className={`text-sm font-black tracking-tight uppercase transition-colors duration-500 ${isSelected ? 'text-white' : 'text-gray-500'}`}>{opt}</span>
                                        <span className="text-[8px] font-black text-gray-800 uppercase tracking-widest mt-1">NODE_IDENTIFIER_{label}</span>
                                    </div>
                                </button>
                            );
                        })}
                    </div>
                ) : (
                    <div className="relative group bg-black/40 rounded-[2rem] overflow-hidden">
                        <div className="absolute top-0 right-0 p-8 opacity-[0.03] text-6xl font-black font-cyber select-none pointer-events-none italic">TEXT_STREAM</div>
                        <textarea
                            value={value?.code || value || ''}
                            onChange={(e) => onChange(e.target.value)}
                            className="w-full h-72 bg-transparent border-2 border-white/5 rounded-[2rem] p-10 text-white font-sans text-base focus:border-teal-500/30 outline-none transition-all duration-700 leading-relaxed placeholder:text-gray-800 font-bold selection:bg-teal-500/30 shadow-inner"
                            placeholder="Initializing subjective evaluation input stream... Minimum 512 tokens recommended for high integrity score."
                        />
                        <div className="absolute bottom-6 right-8 flex gap-2">
                            <div className="w-1.5 h-1.5 rounded-full bg-teal-500/20"></div>
                            <div className="w-1.5 h-1.5 rounded-full bg-teal-500/40"></div>
                            <div className="w-1.5 h-1.5 rounded-full bg-teal-500"></div>
                        </div>
                    </div>
                )}
            </div>
        </section>
    );
}
